"""Microresource display names imported from FDevIDs.

AUTO-GENERATED - do not hand-edit. Regenerate with `npm run update-names`,
which pulls Component/Item/Data rows from:
  https://raw.githubusercontent.com/EDCD/FDevIDs/master/microresources.csv
"""

from __future__ import annotations

from typing import Dict

# Keys are canonicalised (lowercase, no spaces) Frontier internal names.
FDEVIDS_DISPLAY_NAMES: Dict[str, str] = {
    "accidentlogs": "Accident Logs",
    "aerogel": "Aerogel",
    "agriculturalprocesssample": "Agricultural Process Sample",
    "airqualityreports": "Air Quality Reports",
    "atmosphericdata": "Atmospheric Data",
    "audiologs": "Audio Logs",
    "axcombatlogs": "AX Combat Logs",
    "ballisticsdata": "Ballistics Data",
    "biochemicalagent": "Biochemical Agent",
    "biologicalweapondata": "Biological Weapon Data",
    "biometricdata": "Biometric Data",
    "blacklistdata": "Blacklist Data",
    "bloodtestresults": "Blood Test Results",
    "buildingschematic": "Building Schematic",
    "californium": "Californium",
    "campaignplans": "Campaign Plans",
    "carbonfibreplating": "Carbon Fibre Plating",
    "castfossil": "Cast Fossil",
    "catmedia": "Cat Media",
    "censusdata": "Census Data",
    "chemicalcatalyst": "Chemical Catalyst",
    "chemicalexperimentdata": "Chemical Experiment Data",
    "chemicalformulae": "Chemical Formulae",
    "chemicalinventory": "Chemical Inventory",
    "chemicalpatents": "Chemical Patents",
    "chemicalprocesssample": "Chemical Process Sample",
    "chemicalsample": "Chemical Sample",
    "chemicalsuperbase": "Chemical Superbase",
    "chemicalweapondata": "Chemical Weapon Data",
    "circuitboard": "Circuit Board",
    "circuitswitch": "Circuit Switch",
    "classicentertainment": "Classic Entertainment",
    "cocktailrecipes": "Cocktail Recipes",
    "combatantperformance": "Combatant Performance",
    "combattrainingmaterial": "Combat Training Material",
    "compactlibrary": "Compact Library",
    "compressionliquefiedgas": "Compression-Liquefied Gas",
    "conflicthistory": "Conflict History",
    "criminalrecords": "Criminal Records",
    "cropyieldanalysis": "Crop Yield Analysis",
    "culinaryrecipes": "Culinary Recipes",
    "deepmantlesample": "Deep Mantle Sample",
    "degradedpowerregulator": "Degraded Power Regulator",
    "digitaldesigns": "Digital Designs",
    "dutyrota": "Duty Rota",
    "electricalfuse": "Electrical Fuse",
    "electricalwiring": "Electrical Wiring",
    "electromagnet": "Electromagnet",
    "employeedirectory": "Employee Directory",
    "employeeexpenses": "Employee Expenses",
    "employeegeneticdata": "Employee Genetic Data",
    "employmenthistory": "Employment History",
    "encryptedmemorychip": "Encrypted Memory Chip",
    "enhancedinterrogationrecordings": "Enhanced Interrogation Recordings",
    "epinephrine": "Epinephrine",
    "epoxyadhesive": "Epoxy Adhesive",
    "espionagematerial": "Espionage Material",
    "evacuationprotocols": "Evacuation Protocols",
    "explorationjournals": "Exploration Journals",
    "extractionyielddata": "Extraction Yield Data",
    "factionassociates": "Faction Associates",
    "factiondonatorlist": "Faction Donator List",
    "factionnews": "Faction News",
    "financialprojections": "Financial Projections",
    "fleetregistry": "Fleet Registry",
    "genesequencingdata": "Gene Sequencing Data",
    "geneticrepairmeds": "Genetic Repair Meds",
    "geneticresearch": "Genetic Research",
    "geneticsample": "Biological Sample",
    "geologicaldata": "Geological Data",
    "gmeds": "G-Meds",
    "graphene": "Graphene",
    "healthmonitor": "Health Monitor",
    "hush": "Hush",
    "hydroponicdata": "Hydroponic Data",
    "incidentlogs": "Incident Logs",
    "inertiacanister": "Inertia Canister",
    "infinity": "Infinity",
    "influenceprojections": "Influence Projections",
    "inorganiccontaminant": "Inorganic Contaminant",
    "insight": "Insight",
    "insightdatabank": "Insight Data Bank",
    "insightentertainmentsuite": "Insight Entertainment Suite",
    "internalcorrespondence": "Internal Correspondence",
    "interrogationrecordings": "Interrogation Recordings",
    "interviewrecordings": "Interview Recordings",
    "ionbattery": "Ion Battery",
    "ionisedgas": "Ionised Gas",
    "jobapplications": "Job Applications",
    "kompromat": "Kompromat",
    "largecapacitypowerregulator": "Power Regulator",
    "lazarus": "Lazarus",
    "literaryfiction": "Literary Fiction",
    "maintenancelogs": "Maintenance Logs",
    "manufacturinginstructions": "Manufacturing Instructions",
    "medicalrecords": "Medical Records",
    "medicaltrialrecords": "Clinical Trial Records",
    "meetingminutes": "Meeting Minutes",
    "memorychip": "Memory Chip",
    "metalcoil": "Metal Coil",
    "microbialinhibitor": "Microbial Inhibitor",
    "microelectrode": "Microelectrode",
    "microhydraulics": "Micro Hydraulics",
    "microsupercapacitor": "Micro Supercapacitor",
    "microthrusters": "Micro Thrusters",
    "microtransformer": "Micro Transformer",
    "mineralsurvey": "Mineral Survey",
    "mininganalytics": "Mining Analytics",
    "motor": "Motor",
    "multimediaentertainment": "Multimedia Entertainment",
    "mutageniccatalyst": "Mutagenic Catalyst",
    "networkaccesshistory": "Network Access History",
    "networksecurityprotocols": "Network Security Protocols",
    "nextofkinrecords": "Next of Kin Records",
    "nocdata": "NOC Data",
    "nutritionalconcentrate": "Nutritional Concentrate",
    "operationalmanual": "Operational Manual",
    "opinionpolls": "Opinion Polls",
    "opticalfibre": "Optical Fibre",
    "opticallens": "Optical Lens",
    "oxygenicbacteria": "Oxygenic Bacteria",
    "patienthistory": "Patient History",
    "patrolroutes": "Patrol Routes",
    "payrollinformation": "Payroll Information",
    "personalcomputer": "Personal Computer",
    "personaldocuments": "Personal Documents",
    "personallogs": "Personal Logs",
    "petrifiedfossil": "Petrified Fossil",
    "pharmaceuticalpatents": "Pharmaceutical Patents",
    "phneutraliser": "pH Neutraliser",
    "photoalbums": "Photo Albums",
    "plantgrowthcharts": "Plant Growth Charts",
    "politicalaffiliations": "Political Affiliations",
    "prisonerlogs": "Prisoner Logs",
    "productionreports": "Production Reports",
    "productionschedule": "Production Schedule",
    "propaganda": "Propaganda",
    "purchaserecords": "Purchase Records",
    "purchaserequests": "Purchase Requests",
    "push": "Push",
    "pyrolyticcatalyst": "Pyrolytic Catalyst",
    "radioactivitydata": "Radioactivity Data",
    "rdx": "RDX",
    "reactoroutputreview": "Reactor Output Review",
    "recyclinglogs": "Recycling Logs",
    "refinementprocesssample": "Refinement Process Sample",
    "residentialdirectory": "Residential Directory",
    "riskassessments": "Risk Assessments",
    "salesrecords": "Sales Records",
    "scrambler": "Scrambler",
    "securityexpenses": "Security Expenses",
    "seedgeneaology": "Seed Geneaology",
    "settlementassaultplans": "Settlement Assault Plans",
    "settlementdefenceplans": "Settlement Defence Plans",
    "shareholderinformation": "Shareholder Information",
    "shipschematic": "Ship Schematic",
    "slushfundlogs": "Slush Fund Logs",
    "smearcampaignplans": "Smear Campaign Plans",
    "spectralanalysisdata": "Spectral Analysis Data",
    "spyware": "Spyware",
    "stellaractivitylogs": "Stellar Activity Logs",
    "suitschematic": "Suit Schematic",
    "surveillanceequipment": "Surveillance Equipment",
    "surveilleancelogs": "Surveillance Logs",
    "syntheticgenome": "Synthetic Genome",
    "syntheticpathogen": "Synthetic Pathogen",
    "tacticalplans": "Tactical Plans",
    "taxrecords": "Tax Records",
    "titaniumplating": "Titanium Plating",
    "topographicalsurveys": "Topographical Surveys",
    "transmitter": "Transmitter",
    "travelpermits": "Travel Permits",
    "troopdeploymentrecords": "Troop Deployment Records",
    "trueformfossil": "True Form Fossil",
    "tungstencarbide": "Tungsten Carbide",
    "unionmembership": "Union Membership",
    "universaltranslator": "Universal Translator",
    "vaccinationrecords": "Vaccination Records",
    "vaccineresearch": "Vaccine Research",
    "vehicleschematic": "Vehicle Schematic",
    "vipsecuritydetail": "VIP Security Detail",
    "virologydata": "Virology Data",
    "virus": "Virus",
    "viscoelasticpolymer": "Viscoelastic Polymer",
    "visitorregister": "Visitor Register",
    "weaponcomponent": "Weapon Component",
    "weaponinventory": "Weapon Inventory",
    "weaponschematic": "Weapon Schematic",
    "weapontestdata": "Weapon Test Data",
    "xenodefenceprotocols": "Xeno-Defence Protocols",
}
