"""Commodity names imported from FDevIDs.

AUTO-GENERATED - do not hand-edit. Regenerate by re-importing the Commodity rows from:
  https://raw.githubusercontent.com/EDCD/FDevIDs/master/commodity.csv
(rows in the NonMarketable category - Limpets - are left out). Spansh's market search uses
these exact names, e.g. "Void Opal" (not the journal's "Void Opals"); checked 2026-10-09.
"""

from __future__ import annotations

from typing import Tuple

# (Frontier symbol, display name, category)
COMMODITY_ROWS: Tuple[Tuple[str, str, str], ...] = (
    ('AgronomicTreatment', 'Agronomic Treatment', 'Chemicals'),
    ('Explosives', 'Explosives', 'Chemicals'),
    ('Helium', 'Helium', 'Chemicals'),
    ('Helium3', 'Helium-3', 'Chemicals'),
    ('HydrogenFuel', 'Hydrogen Fuel', 'Chemicals'),
    ('HydrogenPeroxide', 'Hydrogen Peroxide', 'Chemicals'),
    ('LiquidOxygen', 'Liquid oxygen', 'Chemicals'),
    ('MineralOil', 'Mineral Oil', 'Chemicals'),
    ('NerveAgents', 'Nerve Agents', 'Chemicals'),
    ('Pesticides', 'Pesticides', 'Chemicals'),
    ('RockforthFertiliser', 'Rockforth Fertiliser', 'Chemicals'),
    ('SurfaceStabilisers', 'Surface Stabilisers', 'Chemicals'),
    ('SyntheticReagents', 'Synthetic Reagents', 'Chemicals'),
    ('Tritium', 'Tritium', 'Chemicals'),
    ('Water', 'Water', 'Chemicals'),
    ('Clothing', 'Clothing', 'Consumer Items'),
    ('ConsumerTechnology', 'Consumer Technology', 'Consumer Items'),
    ('DomesticAppliances', 'Domestic Appliances', 'Consumer Items'),
    ('EvacuationShelter', 'Evacuation Shelter', 'Consumer Items'),
    ('SurvivalEquipment', 'Survival Equipment', 'Consumer Items'),
    ('TrinketsOfFortune', 'Trinkets of Hidden Fortune', 'Consumer Items'),
    ('Algae', 'Algae', 'Foods'),
    ('Animalmeat', 'Animal Meat', 'Foods'),
    ('Coffee', 'Coffee', 'Foods'),
    ('Fish', 'Fish', 'Foods'),
    ('FoodCartridges', 'Food Cartridges', 'Foods'),
    ('FruitAndVegetables', 'Fruit and Vegetables', 'Foods'),
    ('Grain', 'Grain', 'Foods'),
    ('SyntheticMeat', 'Synthetic Meat', 'Foods'),
    ('Tea', 'Tea', 'Foods'),
    ('CeramicComposites', 'Ceramic Composites', 'Industrial Materials'),
    ('CMMComposite', 'CMM Composite', 'Industrial Materials'),
    ('CuratedCommodity', 'Curated Commodity Package', 'Industrial Materials'),
    ('InsulatingMembrane', 'Insulating Membrane', 'Industrial Materials'),
    ('MetaAlloys', 'Meta-Alloys', 'Industrial Materials'),
    ('CoolingHoses', 'Micro-weave Cooling Hoses', 'Industrial Materials'),
    ('NeofabricInsulation', 'Neofabric Insulation', 'Industrial Materials'),
    ('Polymers', 'Polymers', 'Industrial Materials'),
    ('Semiconductors', 'Semiconductors', 'Industrial Materials'),
    ('Superconductors', 'Superconductors', 'Industrial Materials'),
    ('Beer', 'Beer', 'Legal Drugs'),
    ('BootlegLiquor', 'Bootleg Liquor', 'Legal Drugs'),
    ('Liquor', 'Liquor', 'Legal Drugs'),
    ('BasicNarcotics', 'Narcotics', 'Legal Drugs'),
    ('OnionHeadC', 'Onionhead Gamma Strain', 'Legal Drugs'),
    ('Tobacco', 'Tobacco', 'Legal Drugs'),
    ('Wine', 'Wine', 'Legal Drugs'),
    ('ArticulationMotors', 'Articulation Motors', 'Machinery'),
    ('AtmosphericExtractors', 'Atmospheric Processors', 'Machinery'),
    ('BuildingFabricators', 'Building Fabricators', 'Machinery'),
    ('CropHarvesters', 'Crop Harvesters', 'Machinery'),
    ('EmergencyPowerCells', 'Emergency Power Cells', 'Machinery'),
    ('PowerGridAssembly', 'Energy Grid Assembly', 'Machinery'),
    ('ExhaustManifold', 'Exhaust Manifold', 'Machinery'),
    ('GeologicalEquipment', 'Geological Equipment', 'Machinery'),
    ('HeatsinkInterlink', 'Heatsink Interlink', 'Machinery'),
    ('HNShockMount', 'HN Shock Mount', 'Machinery'),
    ('IonDistributor', 'Ion Distributor', 'Machinery'),
    ('MagneticEmitterCoil', 'Magnetic Emitter Coil', 'Machinery'),
    ('MarineSupplies', 'Marine Equipment', 'Machinery'),
    ('HeliostaticFurnaces', 'Microbial Furnaces', 'Machinery'),
    ('MineralExtractors', 'Mineral Extractors', 'Machinery'),
    ('ModularTerminals', 'Modular Terminals', 'Machinery'),
    ('PowerConverter', 'Power Converter', 'Machinery'),
    ('PowerGenerators', 'Power Generators', 'Machinery'),
    ('PowerTransferConduits', 'Power Transfer Bus', 'Machinery'),
    ('RadiationBaffle', 'Radiation Baffle', 'Machinery'),
    ('ReinforcedMountingPlate', 'Reinforced Mounting Plate', 'Machinery'),
    ('SkimerComponents', 'Skimmer Components', 'Machinery'),
    ('ThermalCoolingUnits', 'Thermal Cooling Units', 'Machinery'),
    ('WaterPurifiers', 'Water Purifiers', 'Machinery'),
    ('AdvancedMedicines', 'Advanced Medicines', 'Medicines'),
    ('AgriculturalMedicines', 'Agri-Medicines', 'Medicines'),
    ('BasicMedicines', 'Basic Medicines', 'Medicines'),
    ('CombatStabilisers', 'Combat Stabilisers', 'Medicines'),
    ('PerformanceEnhancers', 'Performance Enhancers', 'Medicines'),
    ('ProgenitorCells', 'Progenitor Cells', 'Medicines'),
    ('Aluminium', 'Aluminium', 'Metals'),
    ('Beryllium', 'Beryllium', 'Metals'),
    ('Bismuth', 'Bismuth', 'Metals'),
    ('Cobalt', 'Cobalt', 'Metals'),
    ('Copper', 'Copper', 'Metals'),
    ('Gallium', 'Gallium', 'Metals'),
    ('Gold', 'Gold', 'Metals'),
    ('Hafnium178', 'Hafnium 178', 'Metals'),
    ('Indium', 'Indium', 'Metals'),
    ('Iridium', 'Iridium', 'Metals'),
    ('Lanthanum', 'Lanthanum', 'Metals'),
    ('Lithium', 'Lithium', 'Metals'),
    ('Osmium', 'Osmium', 'Metals'),
    ('Palladium', 'Palladium', 'Metals'),
    ('Platinum', 'Platinum', 'Metals'),
    ('Praseodymium', 'Praseodymium', 'Metals'),
    ('Samarium', 'Samarium', 'Metals'),
    ('Silver', 'Silver', 'Metals'),
    ('Steel', 'Steel', 'Metals'),
    ('Tantalum', 'Tantalum', 'Metals'),
    ('Thallium', 'Thallium', 'Metals'),
    ('Thorium', 'Thorium', 'Metals'),
    ('Titanium', 'Titanium', 'Metals'),
    ('Uranium', 'Uranium', 'Metals'),
    ('Alexandrite', 'Alexandrite', 'Minerals'),
    ('Bastnasite', 'Bastnasite', 'Minerals'),
    ('Bauxite', 'Bauxite', 'Minerals'),
    ('Benitoite', 'Benitoite', 'Minerals'),
    ('Bertrandite', 'Bertrandite', 'Minerals'),
    ('Bromellite', 'Bromellite', 'Minerals'),
    ('Coltan', 'Coltan', 'Minerals'),
    ('Cryolite', 'Cryolite', 'Minerals'),
    ('Deuterium', 'Deuterium', 'Minerals'),
    ('Diamond', 'Diamond', 'Minerals'),
    ('Gallite', 'Gallite', 'Minerals'),
    ('Goslarite', 'Goslarite', 'Minerals'),
    ('Grandidierite', 'Grandidierite', 'Minerals'),
    ('Haematite', 'Haematite', 'Minerals'),
    ('Indite', 'Indite', 'Minerals'),
    ('Jadeite', 'Jadeite', 'Minerals'),
    ('Lepidolite', 'Lepidolite', 'Minerals'),
    ('LithiumHydroxide', 'Lithium Hydroxide', 'Minerals'),
    ('LowTemperatureDiamond', 'Low Temperature Diamonds', 'Minerals'),
    ('Magnesite', 'Magnesite', 'Minerals'),
    ('MethaneClathrate', 'Methane Clathrate', 'Minerals'),
    ('MethanolMonohydrateCrystals', 'Methanol Monohydrate Crystals', 'Minerals'),
    ('Moissanite', 'Moissanite', 'Minerals'),
    ('Monazite', 'Monazite', 'Minerals'),
    ('Musgravite', 'Musgravite', 'Minerals'),
    ('Olivine', 'Olivine', 'Minerals'),
    ('Painite', 'Painite', 'Minerals'),
    ('PericlaseDunite', 'Periclase Dunite', 'Minerals'),
    ('Pyrophyllite', 'Pyrophyllite', 'Minerals'),
    ('QuartzPyroxenite', 'Quartz Pyroxenite', 'Minerals'),
    ('Rhodplumsite', 'Rhodplumsite', 'Minerals'),
    ('Ruby', 'Ruby', 'Minerals'),
    ('Rutile', 'Rutile', 'Minerals'),
    ('Sapphire', 'Sapphire', 'Minerals'),
    ('Serendibite', 'Serendibite', 'Minerals'),
    ('Taaffeite', 'Taaffeite', 'Minerals'),
    ('Thortveitite', 'Thortveitite', 'Minerals'),
    ('Uraninite', 'Uraninite', 'Minerals'),
    ('Opal', 'Void Opal', 'Minerals'),
    ('AiRelics', 'AI Relics', 'Salvage'),
    ('USSCargoAncientArtefact', 'Ancient Artefact', 'Salvage'),
    ('AncientKey', 'Ancient Key', 'Salvage'),
    ('P_ParticulateSample', 'Anomaly Particles', 'Salvage'),
    ('AntimatterContainmentUnit', 'Antimatter Containment Unit', 'Salvage'),
    ('AntiqueJewellery', 'Antique Jewellery', 'Salvage'),
    ('Antiquities', 'Antiquities', 'Salvage'),
    ('AssaultPlans', 'Assault Plans', 'Salvage'),
    ('USSCargoBlackBox', 'Black Box', 'Salvage'),
    ('ThargoidBoneFragments', 'Bone Fragments', 'Salvage'),
    ('ThargoidGeneratorTissueSample', 'Caustic Tissue Sample', 'Salvage'),
    ('ComercialSamples', 'Commercial Samples', 'Salvage'),
    ('CoralSap', 'Coral Sap', 'Salvage'),
    ('ThargoidCystSpecimen', 'Cyst Specimen', 'Salvage'),
    ('DamagedEscapePod', 'Damaged Escape Pod', 'Salvage'),
    ('DataCore', 'Data Core', 'Salvage'),
    ('DiplomaticBag', 'Diplomatic Bag', 'Salvage'),
    ('EarthRelics', 'Earth Relics', 'Salvage'),
    ('EncryptedCorrespondence', 'Encrypted Correspondence', 'Salvage'),
    ('EncriptedDataStorage', 'Encrypted Data Storage', 'Salvage'),
    ('USSCargoExperimentalChemicals', 'Experimental Chemicals', 'Salvage'),
    ('FossilRemnants', 'Fossil Remnants', 'Salvage'),
    ('GeneBank', 'Gene Bank', 'Salvage'),
    ('GeologicalSamples', 'Geological Samples', 'Salvage'),
    ('AncientCasket', 'Guardian Casket', 'Salvage'),
    ('AncientOrb', 'Guardian Orb', 'Salvage'),
    ('AncientRelic', 'Guardian Relic', 'Salvage'),
    ('AncientTablet', 'Guardian Tablet', 'Salvage'),
    ('AncientTotem', 'Guardian Totem', 'Salvage'),
    ('AncientUrn', 'Guardian Urn', 'Salvage'),
    ('Hostage', 'Hostages', 'Salvage'),
    ('UnknownMineral', 'Impure Spire Mineral', 'Salvage'),
    ('LargeExplorationDataCash', 'Large Survey Data Cache', 'Salvage'),
    ('MilitaryIntelligence', 'Military Intelligence', 'Salvage'),
    ('USSCargoMilitaryPlans', 'Military Plans', 'Salvage'),
    ('M_TissueSample_Nerves', 'Mollusc Brain Tissue', 'Salvage'),
    ('M_TissueSample_Fluid', 'Mollusc Fluid', 'Salvage'),
    ('M3_TissueSample_Membrane', 'Mollusc Membrane', 'Salvage'),
    ('M3_TissueSample_Mycelium', 'Mollusc Mycelium', 'Salvage'),
    ('M_TissueSample_Soft', 'Mollusc Soft Tissue', 'Salvage'),
    ('M3_TissueSample_Spores', 'Mollusc Spores', 'Salvage'),
    ('MysteriousIdol', 'Mysterious Idol', 'Salvage'),
    ('OccupiedCryoPod', 'Occupied Escape Pod', 'Salvage'),
    ('ThargoidOrganSample', 'Organ Sample', 'Salvage'),
    ('PersonalEffects', 'Personal Effects', 'Salvage'),
    ('S_TissueSample_Cells', 'Pod Core Tissue', 'Salvage'),
    ('S_TissueSample_Surface', 'Pod Dead Tissue', 'Salvage'),
    ('S6_TissueSample_Mesoglea', 'Pod Mesoglea', 'Salvage'),
    ('S6_TissueSample_Cells', 'Pod Outer Tissue', 'Salvage'),
    ('S6_TissueSample_Coenosarc', 'Pod Shell Tissue', 'Salvage'),
    ('S_TissueSample_Core', 'Pod Surface Tissue', 'Salvage'),
    ('S9_TissueSample_Shell', 'Pod Tissue', 'Salvage'),
    ('PoliticalPrisoner', 'Political Prisoners', 'Salvage'),
    ('PreciousGems', 'Precious Gems', 'Salvage'),
    ('ProhibitedResearchMaterials', 'Prohibited Research Materials', 'Salvage'),
    ('UnknownSack', 'Protective Membrane Scrap', 'Salvage'),
    ('USSCargoPrototypeTech', 'Prototype Tech', 'Salvage'),
    ('USSCargoRareArtwork', 'Rare Artwork', 'Salvage'),
    ('USSCargoRebelTransmissions', 'Rebel Transmissions', 'Salvage'),
    ('SAP8CoreContainer', 'SAP 8 Core Container', 'Salvage'),
    ('ScientificResearch', 'Scientific Research', 'Salvage'),
    ('ScientificSamples', 'Scientific Samples', 'Salvage'),
    ('UnknownRefinedMineral', 'Semi-Refined Spire Mineral', 'Salvage'),
    ('SmallExplorationDataCash', 'Small Survey Data Cache', 'Salvage'),
    ('SpacePioneerRelics', 'Space Pioneer Relics', 'Salvage'),
    ('TacticalData', 'Tactical Data', 'Salvage'),
    ('USSCargoTechnicalBlueprints', 'Technical Blueprints', 'Salvage'),
    ('ThargoidTissueSampleType2', 'Thargoid Basilisk Tissue Sample', 'Salvage'),
    ('UnknownBiologicalMatter', 'Thargoid Biological Matter', 'Salvage'),
    ('ThargoidTissueSampleType1', 'Thargoid Cyclops Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType6', 'Thargoid Glaive Tissue Sample', 'Salvage'),
    ('ThargoidHeart', 'Thargoid Heart', 'Salvage'),
    ('ThargoidTissueSampleType4', 'Thargoid Hydra Tissue Sample', 'Salvage'),
    ('UnknownArtifact3', 'Thargoid Link', 'Salvage'),
    ('ThargoidTissueSampleType3', 'Thargoid Medusa Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType5', 'Thargoid Orthrus Tissue Sample', 'Salvage'),
    ('UnknownArtifact2', 'Thargoid Probe', 'Salvage'),
    ('UnknownResin', 'Thargoid Resin', 'Salvage'),
    ('ThargoidScoutTissueSample', 'Thargoid Scout Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType7', 'Thargoid Scythe Tissue Sample', 'Salvage'),
    ('UnknownArtifact', 'Thargoid Sensor', 'Salvage'),
    ('UnknownTechnologySamples', 'Thargoid Technology Samples', 'Salvage'),
    ('TimeCapsule', 'Time Capsule', 'Salvage'),
    ('ThargoidTissueSampleType9a', 'Titan Deep Tissue Sample', 'Salvage'),
    ('ThargoidTitanDriveComponent', 'Titan Drive Component', 'Salvage'),
    ('ThargoidTissueSampleType10a', 'Titan Maw Deep Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType10c', 'Titan Maw Partial Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType10b', 'Titan Maw Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType9c', 'Titan Partial Tissue Sample', 'Salvage'),
    ('ThargoidTissueSampleType9b', 'Titan Tissue Sample', 'Salvage'),
    ('USSCargoTradeData', 'Trade Data', 'Salvage'),
    ('AncientRelicTG', 'Unclassified Relic', 'Salvage'),
    ('UnocuppiedEscapePod', 'Unoccupied Escape Pod', 'Salvage'),
    ('UnstableDataCore', 'Unstable Data Core', 'Salvage'),
    ('WreckageComponents', 'Wreckage Components', 'Salvage'),
    ('ThargoidPod', 'Xenobiological Prison Pod', 'Salvage'),
    ('ImperialSlaves', 'Imperial Slaves', 'Slavery'),
    ('Slaves', 'Slaves', 'Slavery'),
    ('AdvancedCatalysers', 'Advanced Catalysers', 'Technology'),
    ('AnimalMonitors', 'Animal Monitors', 'Technology'),
    ('AquaponicSystems', 'Aquaponic Systems', 'Technology'),
    ('AutoFabricators', 'Auto-Fabricators', 'Technology'),
    ('BioReducingLichen', 'Bioreducing Lichen', 'Technology'),
    ('ComputerComponents', 'Computer Components', 'Technology'),
    ('HazardousEnvironmentSuits', 'H.E. Suits', 'Technology'),
    ('DiagnosticSensor', 'Hardware Diagnostic Sensor', 'Technology'),
    ('TerrainEnrichmentSystems', 'Land Enrichment Systems', 'Technology'),
    ('MedicalDiagnosticEquipment', 'Medical Diagnostic Equipment', 'Technology'),
    ('MicroControllers', 'Micro Controllers', 'Technology'),
    ('MuTomImager', 'Muon Imager', 'Technology'),
    ('Nanobreakers', 'Nanobreakers', 'Technology'),
    ('ResonatingSeparators', 'Resonating Separators', 'Technology'),
    ('Robotics', 'Robotics', 'Technology'),
    ('StructuralRegulators', 'Structural Regulators', 'Technology'),
    ('TelemetrySuite', 'Telemetry Suite', 'Technology'),
    ('ConductiveFabrics', 'Conductive Fabrics', 'Textiles'),
    ('Leather', 'Leather', 'Textiles'),
    ('MilitaryGradeFabrics', 'Military Grade Fabrics', 'Textiles'),
    ('NaturalFabrics', 'Natural Fabrics', 'Textiles'),
    ('SyntheticFabrics', 'Synthetic Fabrics', 'Textiles'),
    ('Biowaste', 'Biowaste', 'Waste'),
    ('ChemicalWaste', 'Chemical Waste', 'Waste'),
    ('Scrap', 'Scrap', 'Waste'),
    ('ToxicWaste', 'Toxic Waste', 'Waste'),
    ('BattleWeapons', 'Battle Weapons', 'Weapons'),
    ('Landmines', 'Landmines', 'Weapons'),
    ('NonLethalWeapons', 'Non-Lethal Weapons', 'Weapons'),
    ('PersonalWeapons', 'Personal Weapons', 'Weapons'),
    ('ReactiveArmour', 'Reactive Armour', 'Weapons'),
)
